apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
  namespace: wisecow
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: docker.io/yathindrab/wisecow:latest  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4499
        env:
        - name: SRVPORT
          value: "4499"
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-svc
  namespace: wisecow
spec:
  selector:
    app: wisecow
  ports:
    - name: http
      port: 80
      targetPort: 4499
  type: ClusterIP

